<a href="https://colab.research.google.com/github/Uz8351/MyPhython/blob/master/Copia_de_MATRIZ.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Matriz1=([[1,2,3,4,3],
          [5,6,7,8,2],
          [9,1,4,6,3],
          [5,4,3,2,2],
          [3,4,5,4,1]])



Matriz2=([[4,2,3,4,5],
          [5,8,7,7,4],
          [9,3,4,6,2],
          [5,5,3,1,2],
          [5,4,6,7,1]])

# Multiplicar las matrices
resultado =(Matriz1@Matriz2)

# Imprimir el resultado
print("Matriz resultante:")
print(resultado)

In [ ]:
import numpy as np


Matriz1 = [[1, 2, 3, 4,3],
           [5, 6, 7, 8,2],
           [9, 1, 4, 6,1],
           [5, 4, 3, 2,5],
           [3, 4, 5, 4,6]]

Matriz2 = [[4, 2, 3, 4,3],
           [5, 8, 7, 7,7],
           [9, 3, 4, 6,5],
           [5, 5, 3, 1,4],
           [5, 4, 6, 7,3]]


resultado=(Matriz1@Matriz2)
print(resultado)



In [ ]:
import numpy as np

# Definir las matrices
Matriz1 = np.array([[1, 2, 3, 4, 3],
                   [5, 6, 7, 8, 2],
                   [9, 1, 4, 6, 1],
                   [5, 4, 3, 2, 5],
                   [3, 3, 7, 9, 2],
                   [3, 4, 5, 4, 6]])

Matriz2 = np.array([[4, 2, 3, 4, 3,3,5],
                   [5, 8, 7, 7, 7,6,7],
                   [9, 3, 4, 6, 5,8,6],
                   [5, 5, 3, 1, 4,9,4],
                   [5, 4, 6, 7, 3,7,3]])

# Multiplicar las matrices utilizando la notación @
resultado = Matriz1 @ Matriz2

# Imprimir la matriz resultante
print("Matriz resultante:")
print(resultado)
print("Matriz resultante con dot:")
resultado2 = np.dot(Matriz1, Matriz2)
print(resultado2)


Matriz resultante:
[[ 76  59  59  61  57  96  62]
 [163 127 121 126 130 193 147]
 [112  72  74  80  81 126 103]
 [102  81  91 103  81 116  94]
 [145 104  97  98 107 178 120]
 [127  97 105 116  96 151 107]]
Matriz resultante con dot:
[[ 76  59  59  61  57  96  62]
 [163 127 121 126 130 193 147]
 [112  72  74  80  81 126 103]
 [102  81  91 103  81 116  94]
 [145 104  97  98 107 178 120]
 [127  97 105 116  96 151 107]]


In [ ]:
Matriz1 = [
    [1, 2, 3, 4, 3],
    [5, 6, 7, 8, 2],
    [9, 1, 4, 6, 3],
    [5, 4, 3, 2, 2],
    [3, 4, 5, 4, 1]
]

# Función para imprimir la matriz
def imprimir_matriz(matriz):
    for fila in matriz:
        print(" ".join(map(str, fila)))

# Solicitar al usuario un índice de fila y columna
while True:
    try:
        fila = int(input("Ingrese el índice de la fila (0-4): "))
        columna = int(input("Ingrese el índice de la columna (0-4): "))

        if 0 <= fila < 5 and 0 <= columna < 5:
            valor = Matriz1[fila][columna]
            print(f"El valor en la fila {fila}, columna {columna} es: {valor}")
        else:
            print("Índices fuera de rango. Por favor, ingrese valores válidos (0-4).")
    except ValueError:
        print("Entrada no válida. Ingrese un número entero válido para la fila y la columna.")
    except KeyboardInterrupt:
        print("\nPrograma finalizado.")
        break

# Imprimir la matriz completa
print("\nMatriz completa:")
imprimir_matriz(Matriz1)

In [ ]:

"""
Producira error.
Matriz1, es de dimensión:6,5
Matriz2, es de dimensión:7,5
El numero de colunnas de la primera son 6.
El numero de filas de la segunda son 7.

"""


import numpy as np

# Definir las matrices
Matriz1 = np.array([[1, 2, 3, 4, 3],
                   [5, 6, 7, 8, 2],
                   [9, 1, 4, 6, 1],
                   [5, 4, 3, 2, 5],
                   [3, 3, 7, 9, 2],
                   [3, 4, 5, 4, 6]])

Matriz2 = np.array([[4, 2, 3, 4, 3],
                   [5, 8, 7, 7, 7],
                   [9, 3, 4, 6, 5],
                   [5, 5, 3, 1, 4],
                   [5, 4, 6, 7, 3],
                   [3, 2, 5, 7, 3],
                   [8, 4, 9, 4, 5]])

# Multiplicar las matrices utilizando la notación @
resultado = Matriz1 @ Matriz2

# Imprimir la matriz resultante
print("Matriz resultante:")
print(resultado)
print("Matriz resultante con dot:")
resultado2 = np.dot(Matriz1, Matriz2)
print(resultado2)

In [ ]:
import numpy as np

# Definir las matrices
Matriz1 = np.array([[1, 2, 3, 4, 3],
                   [5, 6, 7, 8, 2],
                   [9, 1, 4, 6, 1],
                   [5, 4, 3, 2, 5],
                   [3, 3, 7, 9, 2],
                   [3, 4, 5, 4, 6]])

Matriz2 = np.array([[4, 2, 3, 4, 3],
                   [5, 8, 7, 7, 7],
                   [9, 3, 4, 6, 5],
                   [5, 5, 3, 1, 4],
                   [5, 4, 6, 7, 3],
                   [3, 2, 5, 7, 3],
                   [8, 4, 9, 4, 5]])

suma=(Matriz1+Matriz2)#ValueError: operands could not be broadcast together with shapes (6,5) (7,5)
print(suma)




In [ ]:
import numpy as np

# Definir las matrices
Matriz1 = np.array([[1, 2, 3, 4, 3],
                   [5, 6, 7, 8, 2],
                   [9, 1, 4, 6, 1],
                   [5, 4, 3, 2, 5],
                   [3, 3, 7, 9, 2],
                   [3, 4, 5, 4, 6]])

Matriz2 = np.array([[4, 2, 3, 4, 3],
                   [5, 8, 7, 7, 7],
                   [9, 3, 4, 6, 5],
                   [5, 5, 3, 1, 4],
                   [5, 4, 6, 7, 3],
                   [3, 2, 5, 7, 3],
                   [8, 4, 9, 4, 5]])

resta=(Matriz1-Matriz2)#ValueError: operands could not be broadcast together with shapes (6,5) (7,5)
print(resta)



In [ ]:
import numpy as np

# Definir las matrices
Matriz1 = np.array([[1, 2, 3, 4, 3],
                   [5, 6, 7, 8, 2],
                   [9, 1, 4, 6, 1],
                   [5, 4, 3, 2, 5],
                   [3, 3, 7, 9, 2],
                   [3, 4, 5, 4, 6]])

Matriz2 = np.array([[4, 2, 3, 4, 3],
                   [5, 8, 7, 7, 7],
                   [9, 3, 4, 6, 5],
                   [5, 5, 3, 1, 4],
                   [5, 4, 6, 7, 3],
                   [3, 2, 5, 7, 3],
                   [8, 4, 9, 4, 5]])

division=(Matriz1/Matriz2)#ValueError: operands could not be broadcast together with shapes (6,5) (7,5)
print(division)


In [ ]:
import numpy as np

Matriz2 = np.array([[4, 2, 3, 4, 3],
                   [5, 8, 7, 7, 7],
                   [9, 3, 4, 6, 5],
                   [5, 5, 3, 1, 4],
                   [5, 4, 6, 7, 3],
                   [3, 2, 5, 7, 3],
                   [8, 4, 9, 4, 5],
                   [8, 4, 9, 4, 5]])

# Obtener las dimensiones de la matriz
filas, columnas = Matriz2.shape
print(f'filas: {filas}, columnas:{columnas}' )
# Recorrer la matriz utilizando un bucle for anidado
for i in range(filas):
    for j in range(columnas):
        elemento = Matriz2[i, j]
        print(f"Matriz2[{i}][{j}] = {elemento}")


In [ ]:
import numpy as np
np.random.seed(0)
X = 2 * np.random.rand(4, 4)
y = 4 + 3 * X + np.random.randn(4, 4)
print("X\n:",X)
print("**************")
print("y\n:",y)
print("**************")
valores = X.dot(y)
print(valores)






X
: [[1.09762701 1.43037873 1.20552675 1.08976637]
 [0.8473096  1.29178823 0.87517442 1.783546  ]
 [1.92732552 0.76688304 1.58345008 1.05778984]
 [1.13608912 1.85119328 0.14207212 0.1742586 ]]
**************
y
: [[ 7.73674426  8.62481053  9.11065933  7.06414083]
 [ 6.8549965   7.02126894  4.07253345 10.0042566 ]
 [10.64641276  5.55848409 11.02010485  5.71900384]
 [ 7.45402588  9.36639598  5.95899556  5.99213457]]
**************
[[39.25498275 36.41798332 35.60431513 35.48810649]
 [38.02268764 37.9479185  33.25305647 34.60126876]
 [44.91106113 40.71657005 44.43551389 36.68116974]
 [24.29104092 25.21815992 20.49362334 28.40199807]]


In [ ]:
import numpy as np
np.random.seed(0)
X = 2 * np.random.rand(4, 2)
y = 4 + 3 * X + np.random.randn(4, 4)
print("X\n:",X)
print("**************")
print("y\n:",y)
print("**************")
valores = X.dot(y)#ValueError: operands could not be broadcast together with shapes (4,2) (4,4)
print(valores)


ValueError: ignored

In [ ]:
import numpy as np
np.random.seed(0)
X = 2 * np.random.rand(4, 4)
y =  X + np.random.randn(4,4)
print("X\n:",X)
print("**************")
print("y\n:",y)
print("**************")
valores = X.dot(y)#
print(valores)


X
: [[1.09762701 1.43037873 1.20552675 1.08976637]
 [0.8473096  1.29178823 0.87517442 1.783546  ]
 [1.92732552 0.76688304 1.58345008 1.05778984]
 [1.13608912 1.85119328 0.14207212 0.1742586 ]]
**************
y
: [[ 1.54149024  1.76405306  2.69960583  0.8846081 ]
 [ 1.1603773   0.43769249 -1.67781539  2.4371646 ]
 [ 2.79176172  0.02471802  3.8532047  -0.39657584]
 [ 1.18184764  1.66400943  1.67485133  1.64361737]]
**************
[[ 8.00524158  4.40551804  7.0335868   5.7701143 ]
 [ 7.35623929  5.04957503  6.47942035  6.48223163]
 [ 9.53158888  5.53487544 11.78932903  4.68459168]
 [ 4.50193156  3.10785457  0.80032243  5.74672845]]
